### ISSUE TITLE
HTTP client for Artipie

### ISSUE THREAD

**Issue by g4s8** [artipie/http-client#1]
Implement reactive HTTP client wrapper for Artipie modules.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#9](https://github.com/artipie/http-client/issues/9) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#10](https://github.com/artipie/http-client/issues/10), [#9](https://github.com/artipie/http-client/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#10](https://github.com/artipie/http-client/issues/10), [#12](https://github.com/artipie/http-client/issues/12), [#9](https://github.com/artipie/http-client/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 4 puzzles [#10](https://github.com/artipie/http-client/issues/10), [#12](https://github.com/artipie/http-client/issues/12), [#25](https://github.com/artipie/http-client/issues/25), [#9](https://github.com/artipie/http-client/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#10](https://github.com/artipie/http-client/issues/10), [#12](https://github.com/artipie/http-client/issues/12), [#9](https://github.com/artipie/http-client/issues/9) are still not solved; solved: [#25](https://github.com/artipie/http-client/issues/25).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#10](https://github.com/artipie/http-client/issues/10), [#12](https://github.com/artipie/http-client/issues/12) are still not solved; solved: [#25](https://github.com/artipie/http-client/issues/25), [#9](https://github.com/artipie/http-client/issues/9).
