### ISSUE TITLE
Jetty leaking connection when body is not read

### ISSUE THREAD

**Issue by olegmoz** [artipie/http-client#23]
Jetty client does not close connection if body is not read. It's hard to enforce all users of client to read body in all cases, but we can read body if it hasn't happen before response handling is complete (response `send` method finished it's async result).

This should solve issue https://github.com/artipie/artipie/issues/401 when `http-client` is adopted in Artipie.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#28](https://github.com/artipie/http-client/issues/28) is still not solved.

**Comment by olegmoz** [comment]
@rultor release, tag=`0.1`

**Comment by olegmoz** [comment]
@yegor256 could you please touch `.rultor.yml` to enable releases in this this repository?

**Comment by yegor256** [comment]
@olegmoz done

**Comment by olegmoz** [comment]
@yegor256 thanks!

**Comment by olegmoz** [comment]
@rultor release, tag=`0.1`

**Comment by olegmoz** [comment]
@yegor256 rultor won't release it as `artipie/http-client` is not friend of `yegor256/artipie-keys`, could you please fix this?

**Comment by yegor256** [comment]
@olegmoz fixed, try again pls

**Comment by olegmoz** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`
