### ISSUE TITLE
HTTP client should support proxy

### ISSUE THREAD

**Issue by olegmoz** [artipie/http-client#5]
HTTP client should support proxy.

How it is done in Artipie:
https://github.com/artipie/artipie/blob/d3a92d28bf13b2dee4eb1c5075bb4daba227ba9e/src/main/java/com/artipie/SliceFromConfig.java#L104-L105

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#19](https://github.com/artipie/http-client/issues/19) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#19](https://github.com/artipie/http-client/issues/19), [#21](https://github.com/artipie/http-client/issues/21) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#19](https://github.com/artipie/http-client/issues/19) is still not solved; solved: [#21](https://github.com/artipie/http-client/issues/21).
