### ISSUE TITLE
Update parent pom

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http-client#78]
We need to update parent pom and fix dependencies issues, that will appear after the update. Also, please, reorganize all the dependencies into groups - main first, tests later. 
Do not add any dependencies from artipie (asto, for example) to avoid cycles in dependencies.

**Comment by olenagerasimova** [comment]
@baudoliver7 hi, would you take this one, please?

**Comment by baudoliver7** [comment]
@olenagerasimova sure :)

**Comment by baudoliver7** [comment]
@olenagerasimova These artipie projects (`vertx-server` and `http`) are mandatory for `http-client`. I think we can't remove them.

**Comment by olenagerasimova** [comment]
@baudoliver7 yes, `vertx-server` and `http` are mandatory, I mean, do not add any more dependencies from artipie
